# Generated by Django 5.2.17 on 2026-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoint',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi tambahan untuk fungsi api ini', null=True),
        ),
    ]
