# Generated by Django 5.2.17 on 2026-09-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='Additional'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='is_create',
            field=models.BooleanField(default=False, verbose_name='Create'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='is_update',
            field=models.BooleanField(default=False, verbose_name='Update'),
        ),
    ]
