# Generated by Django 5.2.17 on 2026-09-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biometric_user_id',
            field=models.CharField(blank=True, help_text='User ID / Enrollment ID yang didaftarkan di mesin ZKTeco', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('check_type', models.CharField(choices=[('I', 'Check In'), ('O', 'Check Out'), ('1', 'Overtime In'), ('2', 'Overtime Out')], default='I', max_length=2)),
                ('sn_device', models.CharField(blank=True, help_text='Serial Number Mesin ZKTeco', max_length=100, null=True)),
                ('raw_uid', models.CharField(help_text='UID Mentah dari Mesin ZK', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='hris_app.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('employee', 'timestamp')},
            },
        ),
        migrations.DeleteModel(
            name='UserAccessAssignment',
        ),
    ]
