# Generated by Django 5.2.17 on 2026-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0002_employee_biometric_user_id_attendancelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama Cronjob / Task', max_length=150)),
                ('code_name', models.CharField(help_text='Kode Unik (contoh: sync_zkteco_attendance)', max_length=100, unique=True)),
                ('schedule', models.CharField(help_text='Format Cron (contoh: */5 * * * *) atau deskripsi teks', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('SUCCESS', 'Sukses'), ('FAILED', 'Gagal'), ('RUNNING', 'Sedang Berjalan'), ('IDLE', 'Belum Diuji')], default='IDLE', max_length=20)),
                ('last_message', models.TextField(blank=True, help_text='Log output atau error message', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
