# Generated by Django 5.2.17 on 2026-09-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0002_apiendpoint_is_additional_apiendpoint_is_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='model_name',
            field=models.CharField(default='General', help_text='Nama Model / Modul (Contoh: Employee, Department, Contract)', max_length=100),
        ),
    ]
