# Generated by Django 5.2.17 on 2026-09-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0002_alter_apiendpoint_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBiometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_face_descriptor', models.TextField(blank=True, null=True)),
                ('encrypted_fingerprint_template', models.TextField(blank=True, null=True)),
                ('device_employee_id', models.CharField(blank=True, help_text='ID karyawan di perangkat biometrik', max_length=100, null=True)),
                ('webauthn_credential_id', models.CharField(blank=True, max_length=550, null=True)),
                ('webauthn_public_key', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeBiometric', to='hris_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Hadir Tepat Waktu'), ('LATE', 'Terlambat'), ('EARLY_LEAVE', 'Pulang Cepat'), ('ABSENT', 'Mangkir / Tanpa Keterangan')], default='PRESENT', max_length=20)),
                ('method', models.CharField(choices=[('FACE', 'Face Recognition'), ('FINGERPRINT', 'Fingerprint Device / WebAuthn'), ('MANUAL', 'Manual Admin Approval')], default='FACE', max_length=20)),
                ('clock_in_lat', models.FloatField(blank=True, null=True)),
                ('clock_in_long', models.FloatField(blank=True, null=True)),
                ('clock_out_lat', models.FloatField(blank=True, null=True)),
                ('clock_out_long', models.FloatField(blank=True, null=True)),
                ('snapshot_image', models.ImageField(blank=True, null=True, upload_to='attendance_snapshots/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hris_app.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
