# Generated by Django 5.2.17 on 2026-09-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0003_cronjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, null=True, verbose_name='Blood Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='employee',
            name='couple_date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Couple Date of Birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='couple_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Couple Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relation',
            field=models.CharField(choices=[('ayah', 'Ayah'), ('ibu', 'Ibu'), ('kakak', 'Kakak'), ('adik', 'Adik'), ('saudara', 'Saudara'), ('pasangan', 'Suami/Istri')], default='ayah', max_length=10, verbose_name='Emergency Contact Relation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_child_date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='First Child Date of Birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_child_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Child Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_local',
            field=models.BooleanField(default=False, verbose_name='Origin Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kelurahan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pants_size',
            field=models.SmallIntegerField(default=30, verbose_name='Pants Size'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='No Whatsapp'),
        ),
        migrations.AddField(
            model_name='employee',
            name='poin_of_hire',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Point Of Hire'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pos_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pos Code'),
        ),
        migrations.AddField(
            model_name='employee',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='employee',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='second_child_date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Second Child Date of Birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='second_child_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Second Child Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='S', max_length=5, verbose_name='Shirt Size'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shoes_size',
            field=models.SmallIntegerField(default=35, verbose_name='Shoes Size'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tangal_induksi',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Induksi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='third_child_date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Third Child Date of Birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='third_child_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Third Child Name'),
        ),
    ]
