# Generated by Django 5.2.17 on 2026-09-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0003_apiendpoint_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='schedule',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='interval_type',
            field=models.CharField(choices=[('minutes', 'Menit'), ('hours', 'Jam'), ('days', 'Hari')], default='minutes', help_text='Satuan waktu (Menit/Jam/Hari)', max_length=10),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='interval_value',
            field=models.PositiveIntegerField(default=5, help_text='Nilai interval (contoh: 5)'),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Jam Mulai (opsional, contoh: 08:00:00)', null=True),
        ),
    ]
