# Generated by Django 5.2.17 on 2026-09-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0004_remove_cronjob_schedule_cronjob_interval_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff / Non-Staff'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='onboarding_id',
            field=models.BigIntegerField(blank=True, max_length=50, null=True, verbose_name='OnBoarding ID'),
        ),
    ]
