# Generated by Django 5.2.17 on 2026-09-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0004_remove_section_department_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_onboarding',
            field=models.BooleanField(default=False, verbose_name='Is Onboarding'),
        ),
    ]
