# Generated by Django 5.2.17 on 2026-09-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0005_employee_is_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
