# Generated by Django 5.2.17 on 2026-09-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0005_alter_employee_is_staff_alter_employee_onboarding_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeStatusHistory',
        ),
    ]
