# Generated by Django 5.2.17 on 2026-09-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0007_alter_employee_company_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_status',
            field=models.CharField(choices=[('TK/0', 'Belum Menikah / Janda (TK/0)'), ('K/0', 'Menikah (K/0)'), ('K/1', 'Menikah, Anak 1 (K/1)'), ('K/2', 'Menikah, Anak 2 (K/2)'), ('K/3', 'Menikah, Anak 3 (K/3)'), ('TK/1', 'Duda, Anak 1 (TK/1)'), ('TK/2', 'Duda, Anak 2 (TK/2)'), ('TK/3', 'Duda, Anak 3 (TK/3)')], default='TK/0', max_length=10, verbose_name='Employee Relation Status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15, verbose_name='Form Status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('progress', 'In Progress'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=15, verbose_name='Status'),
        ),
    ]
