# Generated by Django 5.2.17 on 2026-09-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0009_department_code_position_code_section_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pendidikan',
            field=models.CharField(choices=[('SMA', 'SMA/Sederajat'), ('D3', 'Diploma 3'), ('S1', 'Strata 1'), ('S2', 'Strata 2'), ('S3', 'Strata 3'), ('LAINNYA', 'Lainnya')], default='LAINNYA', max_length=20),
        ),
    ]
