# Generated by Django 5.2.17 on 2026-09-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0010_alter_employee_pendidikan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nik_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
