# Generated by Django 5.2.17 on 2026-09-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0011_alter_employee_nik_karyawan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nik_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
