# Generated by Django 5.2.17 on 2026-09-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0012_alter_employee_nik_karyawan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OnBoarding ID'),
        ),
    ]
