# Generated by Django 5.2.17 on 2026-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0013_employee_onboarding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='zk_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ZKTeco Department ID'),
        ),
        migrations.AddField(
            model_name='position',
            name='zk_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ZKTeco Position ID'),
        ),
        migrations.AddField(
            model_name='section',
            name='zk_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ZKTeco Section ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Department Code'),
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postition Code'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Section Code'),
        ),
    ]
