# Generated by Django 5.2.17 on 2026-09-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0014_department_zk_id_position_zk_id_section_zk_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Area Code')),
                ('zk_id', models.BigIntegerField(blank=True, null=True, verbose_name='ZKTeco Area ID')),
            ],
        ),
    ]
