# Generated by Django 5.2.17 on 2026-09-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0015_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='zk_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ZK Employee Code'),
        ),
    ]
