# Generated by Django 5.2.17 on 2026-09-12 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0016_employee_zk_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Edited'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeEditStagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('progress', 'progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nik_karyawan', models.CharField(blank=True, max_length=50, null=True)),
                ('nik_ktp', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('changes_payload', models.JSONField(help_text='Menyimpan komparasi data sebelum (old) dan sesudah (new)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edit_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_stagging', to='hris_app.employee')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_employee_changes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewed_employee_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
