# Generated by Django 5.2.17 on 2026-09-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0017_employee_is_edited_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='is_crud',
            field=models.BooleanField(default=True, verbose_name='CRUD API'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nik_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeeditstagging',
            name='nik_ktp',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
