# Generated by Django 5.2.17 on 2026-09-14 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0018_apiendpoint_is_crud_alter_employee_nik_karyawan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='zk_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ZkTeco Attendace ID'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_logs', to='hris_app.employee'),
        ),
    ]
