# Generated by Django 5.2.17 on 2026-09-14 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0019_attendancelog_zk_id_alter_attendancelog_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='Area lokasi kerja karyawan (bisa lebih dari satu)', related_name='employees', to='hris_app.area'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_logs', to='hris_app.employee'),
        ),
    ]
