# Generated by Django 5.2.17 on 2026-09-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0020_employee_areas_alter_attendancelog_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Attendance Raw PayLoad'),
        ),
    ]
