# Generated by Django 5.2.17 on 2026-09-15 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0021_attendancelog_raw_payload'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='department_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='employee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='employee_nik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='position_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='hris_app.employee'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Attendance Raw Payload'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='raw_uid',
            field=models.CharField(blank=True, help_text='UID Mentah / emp_code dari Mesin ZK', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='zk_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ZKTeco Attendance ID'),
        ),
    ]
