# Generated by Django 6.0.7 on 2026-07-30 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_code', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hris_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik_karyawan', models.CharField(max_length=50)),
                ('nik_ktp', models.CharField(max_length=16, unique=True)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('join_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('RESIGNED', 'Resign'), ('PROBATION', 'Probation'), ('CONTRACT', 'Kontrak')], default='ACTIVE', max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(choices=[('ISLAM', 'Islam'), ('KRISTEN', 'Kristen'), ('KATOLIK', 'Katolik'), ('HINDU', 'Hindu'), ('BUDDHA', 'Buddha'), ('KONGHUCU', 'Konghucu'), ('LAINNYA', 'Lainnya')], default='ISLAM', max_length=20)),
                ('pendidikan', models.CharField(choices=[('SMA', 'SMA/Sederajat'), ('D3', 'Diploma 3'), ('S1', 'Strata 1'), ('S2', 'Strata 2'), ('S3', 'Strata 3'), ('LAINNYA', 'Lainnya')], max_length=20)),
                ('alamat', models.TextField()),
                ('contact_person', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_relation', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hris_app.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hris_app.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hris_app.position')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hris_app.section')),
            ],
        ),
    ]
