# Generated by Django 6.0.7 on 2026-08-02 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0003_employee_user_alter_employee_agama_apiaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama Paket Akses (Contoh: HR Admin)', max_length=100, unique=True)),
                ('allowed_codenames', models.JSONField(default=list, help_text="List endpoint yang diizinkan, misal: ['api-hris-submission', 'api-general-submission']")),
                ('description', models.TextField(blank=True, help_text='Deskripsi tambahan untuk Paket akses ini', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hris_app.apiaccesstemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'template')},
            },
        ),
        migrations.DeleteModel(
            name='APIAccess',
        ),
    ]
